
services:
  - type: web
    name: phi3-mini-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /
    autoDeploy: true
